default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: mad123  # Use the password you set here

development:
  <<: *default
  database: horizonDB_development

test:
  <<: *default
  database: horizonDB_test

production:
  <<: *default
  database: horizonDB_production
